CREATE DATABASE IF NOT EXISTS cap4770_project;
USE cap4770_project;

CREATE TABLE IF NOT EXISTS flights (
    id INT AUTO_INCREMENT PRIMARY KEY,
    YEAR INT,
    MONTH INT,
    DAY_OF_WEEK INT,
    OP_UNIQUE_CARRIER VARCHAR(10),
    ORIGIN_AIRPORT_ID INT,
    DEST_AIRPORT_ID INT,
    CRS_DEP_TIME VARCHAR(4),
    DEP_DELAY FLOAT,
    TAXI_OUT FLOAT,
    CANCELLED TINYINT,
    DIVERTED TINYINT,
    CRS_ELAPSED_TIME FLOAT,
    AIR_TIME FLOAT,
    DISTANCE FLOAT,
    DISTANCE_GROUP INT
);